version: "3.7"

services:
  mongodb:
    image: mongo:latest
    container_name: formmongo
    env_file:
      - ./server/.env.development
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
    networks:
      - app-network
  webclient:
    container_name: webclient
    image: webclient
    build:
      context: ./webclient
      dockerfile: Dockerfile
    volumes:
      - "./webclient:/app"
      - "/app/node_modules"
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    tty: true
  server:
    container_name: server
    image: server
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - "./server:/app"
      - "/app/node_modules"
    ports:
      - 8080:8080
      - 12345:12345
    networks:
      - app-network
    depends_on:
      - mongodb

volumes:
  mongodb_data_container:

networks:
  app-network:
    driver: bridge
